name: kotlin-language
version: 1.0.0
main: world.kitpvp.kotlinlanguage.KotlinLanguagePlugin
description: Kotlin language extension for paper
api-version: '1.20'
load: POSTWORLD
website: https://github.com/KitPVP-World/KSpigot/