name: $name
version: $version
main: net.axay.plugin.KSpigotPlugin
description: $description
api-version: "$apiVersion"
authors:
  - jakobkmar
contributors:
  - NotStevy
website: https://github.com/KitPVP-World/KSpigot/