# Here lie dragons!
#
# This action either builds the server or
# builds a paperclip jar to be updated in the body
# of the PR relating to this action.

name: Build Paper
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

jobs:
  build:
    # Run on all label events (won't be duplicated) or all push events or on PR syncs not from the same repo
    if: (github.event_name == 'pull_request' && github.event.action == 'labeled') || github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: useblacksmith/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Setup Gradle
        uses: useblacksmith/setup-gradle/setup-gradle@v5
        with:
          gradle-version: 8.12
      - name: Build with Gradle
        run: gradle build publish --stacktrace -PkitpvpWorldRepositoryUsername="${{ secrets.MVNREPO_USERNAME }}"  -PkitpvpWorldRepositoryPassword="${{ secrets.MVNREPO_PASSWORD }}" --no-daemon

      - name: Upload KSpigot
        uses: actions/upload-artifact@v4
        with:
          name: kspigot
          path: build/libs/KSpigot-*.jar

